### PR TITLE
[UniqueEntity] Fixed passing an identifier

### PR DESCRIPTION
**Pull request by recipe**
Fixed bug. UniqueEntity identifier value should not be persisted in cache.

### CODE REVIEW

**Comment by Abhoryo** [comment]
Do you want access to the repository to merge yourself your next changes ?

**Comment by recipe** [comment]
:) Thank you for your confidence. If it's possible I do.

**Comment by Abhoryo** [comment]
Voilà, you can merge yourself this PR.

**Comment by recipe** [comment]
Thanks!

**Pull request merged**
