### PR TITLE
Move the removeErrors

### PR DESCRIPTION
**Pull request by benji07**
I move the removeErrors to handle multiple validator on a single field.

Before, each time you call the checkError your remove the errors from the fields.

Now, we remote the errors before the first check

### CODE REVIEW

**Comment by Abhoryo** [comment]
Maybe we can add an option to choose when errors are removed.

**Comment by recipe** [comment]
I think no need in extra option. We can check whether checkmode `blur` is enabled and remove an old error messages if does.

**Comment by recipe** [comment]
However considering that it is not a solution in the Benjamin's case, anyone can just override `JsFormValidation.js.twig` script placing it to the `app/Resources/APYJsFormValidationBundle/views/Frameworks/JsFormValidation.js.#your_framework#.twig`

**Comment by benji07** [comment]
And after testing this again, it doesn't work as `result = result && checkError` don't call checkError if result is false

**Pull request closed without merging**
