### PR TITLE
Split the FormValidationScriptGenerator::generate() method into two methods...

### PR DESCRIPTION
**Pull request by filips-alpe**
... to simplify customization

### CODE REVIEW

**Comment by filips-alpe** [comment]
Bump! :)

**Comment by Abhoryo** [comment]
Can we split each fonctionnality ?

**Comment by filips-alpe** [comment]
Not sure about 'each' cause this is surely a complicated method but I'd be glad to simplify it more.

**Comment by Abhoryo** [comment]
I hope we can create a method for each type of constraint(getter, entity...)

**Pull request closed without merging**
