### PR TITLE
Ticket #15 Introducing to phpunit testing

### PR DESCRIPTION
**Pull request by recipe**

### CODE REVIEW

**Comment by Abhoryo** [comment]
I've activated travis-ci and there is an error with monolog

http://travis-ci.org/#!/Abhoryo/APYJsFormValidationBundle/jobs/2134791

**Comment by recipe** [comment]
It should have been together with Symfony as Monolog bundle is the part of standard distribution package of symfony 2 .
[https://github.com/symfony/symfony-standard](https://github.com/symfony/symfony-standard)

Maybe, something is wrong in travis config?

**Comment by Abhoryo** [comment]
Like you said, monolog is parted of symfony-standard.

**Comment by recipe** [comment]
Monolog exists only in require-dev env, so we should use it for travis. I do not know how so far. [symfony/composer.json](https://github.com/symfony/symfony/blob/master/composer.json)

**Comment by Abhoryo** [comment]
travis installs only [symfony/symfony](http://packagist.org/packages/symfony/symfony)
Only twig and doctrine are required. To add other bundles we have to switch to the dev env.

**Comment by Abhoryo** [comment]
Maybe we can add require-dev, too

**Comment by Abhoryo** [comment]
I've add the --dev flag to composer.

**Comment by Abhoryo** [comment]
:( not working too.

**Comment by recipe** [comment]
Look [here](https://github.com/schmittjoh/JMSI18nRoutingBundle/blob/master/composer.json).
This bundle uses TestBundle too.
We need in require-dev section of our bundle.

**Comment by recipe** [comment]
And they use `php composer.phar install --dev`  instead.
You used `php composer.phar --dev install`

**Comment by Abhoryo** [comment]
That's not the problem. Monolog is now installed but the kernel doesn't know the namespace.

**Comment by recipe** [comment]
Ok, it is easier. [Looking for other experience](https://github.com/schmittjoh/JMSI18nRoutingBundle/commit/ff29b3dddeb802790ffce506a35e7423bd45a1b2#composer.json) Thinking what we do wrong.

**Comment by recipe** [comment]
I'm going to fix this.

**Comment by Abhoryo** [comment]
Ok, I let you do this.

**Comment by recipe** [comment]
Well done http://travis-ci.org/#!/Abhoryo/APYJsFormValidationBundle/builds/2140608

**Comment by Abhoryo** [comment]
thx.

**Pull request merged**
