### PR TITLE
fixes issue #28

### PR DESCRIPTION
**Pull request by bmurashin**
Changed ExposeTranslation to Translator following BazingaExposeTranslationBundle 0.1.\* change

### CODE REVIEW

**Comment by Abhoryo** [comment]
Thanks

**Comment by yosh778** [comment]
Why not fix 2.0 branch too ?
This bundle is great work, but would still need more work I guess (nested forms, collections, I know it's written in the todo file)
Also I experienced a bug on 2.0 when we don't provide an entity as second parameter when calling createForm in a controller to create our AbstractType child classes, although the getDefaultOptions()['data_class'] method contains the className declared for our AbstractType.
A way to customize the error output like we can with Symfony2's custom_errors form_theme would be nice too lol, but yeah that's quite a lot more work.

Too bad Symfony2 doesn't do all this already, I heard ASP does
Too bad for the classname bug, I'll have to remove the bundle to avoid having to fix all default forms without any entity loaded.

Best luck anyway

**Comment by Abhoryo** [comment]
2.0 branch isn't really supported as Symfony 2.0 will be soon.
The 2.0 doesn't know how to handle form with no entity, the master normally do (See test exemple).

I will soon use this bundle on a big commercial project, so I'll perform quite of enhancements in the next 6 months, I think. I will rethink about the whole thing with Symfony2.3 to make a great bundle I hope.

**Comment by yosh778** [comment]
I guess indeed, we started our project just before 2.1 update lol.
Ok, good luck then.

**Pull request merged**
